index_id: insurance_vectors
control_field_max_length: false
exclude_chunk_from_metadata: false
indexing_options:
  rendered_item:
    indexing_option: main_content
    max: -1
  policy_title:
    indexing_option: contextual_content
    max: -1
  document_title:
    indexing_option: contextual_content
    max: -1
  document_policy:
    indexing_option: contextual_content
    max: -1
  policy_status:
    indexing_option: attributes
    max: -1
  policy_insured:
    indexing_option: attributes
    max: -1
  policy_insurer:
    indexing_option: attributes
    max: -1
  document_policy_id:
    indexing_option: attributes
    max: -1
  document_type:
    indexing_option: attributes
    max: -1
  document_date:
    indexing_option: attributes
    max: -1
  document_tax_years:
    indexing_option: attributes
    max: -1
  document_insured:
    indexing_option: attributes
    max: -1
  document_insurer:
    indexing_option: attributes
    max: -1
  entity_bundle:
    indexing_option: attributes
    max: -1
